# Exercises 8.1

Here I'll load the CSV file but in the notebooks its already in memory from being loaded further up.

## 1.

In [1]:
import pandas as pd
        
        
# Open the csv file as a DataFrame
df = pd.read_csv("../data/PythonExampleCSVfile1.csv", index_col=None)

In [3]:
# Print the requested rows
print(df.loc[49])
print(df.loc[71])
print(df.loc[8])

Name                  XMMXCS J021440.9-043321.9
Redshift                                   0.15
Mean_X                                    4.537
Mean_x_minus_delta                        4.396
Mean_x_plus_delta                          4.68
Mean_y                                     3.56
Mean_y_minus_delta                        3.457
Mean_y_plus_delta                         3.663
Name: 49, dtype: object
Name                  XMMXCS J010608.4+005031.4
Redshift                                   0.26
Mean_X                                    1.925
Mean_x_minus_delta                        1.652
Mean_x_plus_delta                         2.248
Mean_y                                    1.925
Mean_y_minus_delta                        1.652
Mean_y_plus_delta                         2.248
Name: 71, dtype: object
Name                  XMMXCS J014430.3+021237.0
Redshift                                   0.17
Mean_X                                    3.023
Mean_x_minus_delta                        2.279
Mean_x_plus_delta                         4.152
Mean_y                                    8.331
Mean_y_minus_delta                        7.272
Mean_y_plus_delta                         9.165
Name: 8, dtype: object

In [4]:
# Print the requested values 
print(df["Mean_y"][61:71])

61    2.588
62    2.566
63    2.547
64    2.471
65    2.342
66    2.321
67    2.259
68    2.146
69    2.144
70    2.069
Name: Mean_y, dtype: float64

In [5]:
# Define new columns as requested
df["Mean_y_upper"] = df.Mean_y_plus_delta - df.Mean_y
df["Mean_y_lower"] = df.Mean_y - df.Mean_y_minus_delta

In [6]:
# Save this Dataframe
df.to_csv("../data/new_PythonExampleCSVfile1.csv")

In [8]:
# Read it back in
df = pd.read_csv("../data/new_PythonExampleCSVfile1.csv", index_col=None)

df

,Unnamed: 0,Name,Redshift,Mean_X,Mean_x_minus_delta,Mean_x_plus_delta,Mean_y,Mean_y_minus_delta,Mean_y_plus_delta,Mean_y_upper,Mean_y_lower
0,0,XMMXCS J113313.8+662243.9,0.12,5.031,4.805,5.255,11.087,10.239,11.883,0.796,0.848
1,1,XMMXCS J215336.9+174146.4,0.25,10.599,10.301,10.897,10.363,10.066,10.660,0.297,0.297
2,2,XMMXCS J164020.3+464226.2,0.23,10.589,10.134,11.045,10.220,9.875,10.563,0.343,0.345
3,3,XMMXCS J172226.8+320754.3,0.23,8.548,7.972,9.125,9.069,8.490,9.695,0.626,0.579
4,4,XMMXCS J003706.3+090924.6,0.27,9.089,8.794,9.387,8.693,8.401,8.987,0.294,0.292
...,...,...,...,...,...,...,...,...,...,...,...
79,79,XMMXCS J150918.3-001432.7,0.27,1.007,0.748,1.347,1.007,0.748,1.347,0.340,0.259
80,80,XMMXCS J092129.1+370059.9,0.23,1.570,1.468,1.679,0.973,0.856,1.063,0.090,0.117
81,81,XMMXCS J130741.7+292627.9,0.26,0.854,0.540,1.435,0.854,0.540,1.435,0.581,0.314
82,82,XMMXCS J092114.5+370131.3,0.23,0.619,0.464,0.759,0.797,0.691,0.878,0.081,0.106
83,83,XMMXCS J120439.0+352233.2,0.19,0.547,0.403,0.677,0.547,0.433,0.631,0.084,0.114